#!/usr/bin/env python3
"""旧暦（JSTの朔日・中気のない月を閏月）の月表を作り lunar-data.js に書き出す
計算は _check.py の lunar_table と同じ（Swiss Ephemeris）。範囲は天文暦と同じ 1920〜2080年。

lunar-data.js の中身
  LUNAR_START_JDN  最初の月の1日のユリウス通日
  LUNAR_LEN        各月の日数（'9'=29日, '0'=30日）
  LUNAR_NUM        各月の月番号（'a'=1月 … 'l'=12月、大文字は閏月）
  LUNAR_START_YEAR 最初の月が属する旧暦の年
"""
from pathlib import Path
from _check import lunar_table

HERE = Path(__file__).resolve().parent
months = lunar_table(1919, 2081)
lens = "".join("9" if b - a == 29 else "0" for a, b, *_ in months)
assert all(b - a in (29, 30) for a, b, *_ in months)
nums = "".join((chr(96 + n).upper() if leap else chr(96 + n)) for _, _, n, leap, _ in months)
js = (
    "// Auto-generated by generate_lunar.py（旧暦の月表・JST・1919〜2081年）\n"
    f"const LUNAR_START_JDN = {months[0][0]};\n"
    f"const LUNAR_START_YEAR = {months[0][4]};\n"
    f'const LUNAR_LEN = "{lens}";\n'
    f'const LUNAR_NUM = "{nums}";\n'
)
(HERE / "lunar-data.js").write_text(js, encoding="utf-8")
print(len(months), "months,", len(js), "bytes")
